version: '2'

services:
  app:
    build: .
    container_name: anime-iptv-1.1-app
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/data/anime.db
      - LOG_DIR=/logs
      - NGROK_AUTHTOKEN
